version: '2'
services:
  concierge:
    build:
      context: .
    image: razorpay:concierge
    links:
      - db-concierge
    depends_on:
      - db-concierge
    ports:
      - 28070:80
    environment:
      DB_HOST: db-concierge
      DB_DATABASE: concierge
      DB_USERNAME: concierge
      DB_PASSWORD: 123
      APP_ENV: dev
  db-concierge:
    image: mysql:5.6
    ports:
      - 23306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: concierge
      MYSQL_USER: concierge
      MYSQL_PASSWORD: 123
