name: CI

on:
  push:
    branches:
      - '*'

  pull_request:
    branches:
      - '*'

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Hadolint test
      run: |
        wget https://github.com/hadolint/hadolint/releases/download/v1.17.5/hadolint-Linux-x86_64 -O hadolint
        chmod +x hadolint
        ./hadolint Dockerfile

  build:
    runs-on: ubuntu-latest
    needs: ['hadolint']
    steps:
      - uses: actions/checkout@v1

      - name: build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.PUBLIC_DOCKER_USERNAME }}
          password: ${{ secrets.PUBLIC_DOCKER_PASSWORD }}
          repository: razorpay/concierge
          tag_with_ref: true
          tag_with_sha: true
          dockerfile: Dockerfile
