name: CI

on:
  push:
    branches:
      - '*'

  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Get Image Tags
        id: get_tags
        run: |
          BRANCH_NAME=`echo ${GITHUB_REF} | cut -c12- | tr -s ' ' | sed -e 's/\./_/g;s/\//_/g;s/-/_/g'`
          if [ $BRANCH_NAME == "master" ]; then
            echo ::set-output name=name::$GITHUB_REPOSITORY:$BRANCH_NAME-$GITHUB_SHA, $GITHUB_REPOSITORY:$BRANCH_NAME, $GITHUB_REPOSITORY:latest
          else
            echo ::set-output name=name::$GITHUB_REPOSITORY:$BRANCH_NAME-$GITHUB_SHA, $GITHUB_REPOSITORY:$BRANCH_NAME
          fi
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.PUBLIC_DOCKER_USERNAME }}
          password: ${{ secrets.PUBLIC_DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.get_tags.outputs.name }}
