name: Push to Harbor
on:
  push:
    branches:
      - "ingress-concierge"
jobs:
  build-image:
    name: Build image
    runs-on: [ self-hosted ]

    steps:
      - name: image tag
        id: image_tag
        run: |
          BRANCH="$(echo ${GITHUB_REF##*/})";
          IMAGE_TAG=${{ github.sha }};
          echo "commit hash: $IMAGE_TAG";
          if [ "$BRANCH" == "master" ]; then
                  IMAGE_TAG="latest";
          fi
          echo "Branch is : $BRANCH & tag is: $IMAGE_TAG";
          echo ::set-output name=image_tag::$IMAGE_TAG
      - name: Login to Harbor
        uses: docker/login-action@v1
        with:
          registry: c.rzp.io
          username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
          password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: build
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: true
          tags: c.rzp.io/razorpay/concierge:ingress-concierge_${{ steps.image_tag.outputs.image_tag }}
